from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import uvicorn
import json
import logging
import google.generativeai as genai

from sqlalchemy.orm import Session
from database import engine, get_db
import models

# Import API Routers
from routers.upload import router as upload_router
from services.rag_retriever import retrieve_matching_laws
from services.gemini_client import generate_text_completion
from config import GEMINI_API_KEY, OPENROUTER_API_KEY
from routers.auth import router as auth_router

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Configure standard Gemini if key is present
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

# Initialize SQLite database tables on server startup
models.Base.metadata.create_all(bind=engine)

# Seed database with laws if empty
def seed_database_laws():
    db = next(get_db())
    try:
        count = db.query(models.Law).count()
        if count == 0:
            logger.info("Database laws table is empty. Seeding from laws_kb.json...")
            import os
            BASE_DIR = os.path.dirname(os.path.abspath(__file__))
            json_path = os.path.join(BASE_DIR, "data", "laws_kb.json")
            if os.path.exists(json_path):
                with open(json_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    laws = data.get("laws", [])
                    for item in laws:
                        db_law = models.Law(
                            act=item["act"],
                            category=item["category"],
                            scope=item["scope"],
                            summary=item["summary"],
                            details=item["details"],
                            remedies_json=json.dumps(item["remedies"]),
                            keywords_json=json.dumps(item["keywords"])
                        )
                        db.add(db_law)
                    db.commit()
                    logger.info(f"Successfully seeded {len(laws)} laws into SQLite database.")
            else:
                logger.error(f"Seeding failed: {json_path} not found.")
    except Exception as e:
        db.rollback()
        logger.error(f"Failed to seed database: {str(e)}")

seed_database_laws()

app = FastAPI(title="NyayaMitra AI API", version="1.0.0")

# Enable CORS for frontend cross-origin requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "*"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(upload_router)
app.include_router(auth_router)

class ChatMessage(BaseModel):
    role: str # 'user' or 'assistant'
    content: str

class ChatRequest(BaseModel):
    message: str
    document_id: int
    history: List[ChatMessage] = []
    language: Optional[str] = "english"

class TranslateRequest(BaseModel):
    text: str
    target_language: str # e.g. 'telugu'

@app.get("/")
def read_root():
    return {"status": "running", "app": "NyayaMitra AI Backend (SQLite Active)"}

async def perform_translation(text_to_translate: str, target_language: str) -> str:
    lang = target_language.lower()
    if lang != 'telugu':
        return text_to_translate

    if not GEMINI_API_KEY and not OPENROUTER_API_KEY:
        # Static English-to-Telugu translation dictionary for demo fallback
        telugu_dictionary = {
            "1. Document Ingestion": "1. పత్రం అప్‌లోడ్",
            "2. AI Analysis Workspace": "2. ఏఐ విశ్లేషణ విభాగం",
            "Drag & drop your notice file here": "మీ నోటీసు పత్రాన్ని ఇక్కడ డ్రాప్ చేయండి",
            "Supports PDF, PNG, JPEG up to 10MB": "PDF, PNG, JPEG ఫార్మాట్లు (గరిష్టంగా 10MB)",
            "Browse File": "ఫైల్ ఎంచుకోండి",
            "Analyzing legal document...": "పత్రాన్ని విశ్లేషిస్తోంది...",
            "Extracting text with Gemini AI": "జెమిని ఏఐ ద్వారా సమాచారాన్ని సేకరిస్తోంది",
            "Remove": "తొలగించు",
            "Notice File Detail Preview": "పత్రం పాఠ్య వివరణ ప్రివ్యూ",
            "Listen Summary": "సారాంశం వినండి",
            "Pause Audio": "ఆడియో నిలిపివేయండి",
            "Plain Language Explanation": "సాధారణ భాషా వివరణ",
            "Critical Milestones Timeline": "కీలక గడువుల కాలక్రమం",
            "Relevant Legal Citations": "సంబంధిత చట్టపరమైన ఆధారాలు",
            "Recommended Next Steps": "సిఫార్సు చేయబడిన తదుపరి చర్యలు",
            "Autogenerated Response Template": "స్వయంచాలక ప్రత్యుత్తర నమూనా",
            "Your landlord, Greenwood Management, claims you defaulted on July rent of INR 25,000.": "మీ యజమాని గ్రీన్‌వుడ్ మేనేజ్‌మెంట్ మీరు రూ. 25,000 అద్దె చెల్లించలేదని నోటీసు పంపారు.",
            "Verify receipts.": "రశీదులను సరిచూసుకోండి.",
            "Draft legal dispute reply.": "ప్రత్యుత్తర లేఖను సిద్ధం చేయండి."
        }
        return telugu_dictionary.get(text_to_translate, f"[తెలుగు అనువాదం] {text_to_translate}")
    else:
        try:
            translation_prompt = f"Translate the following text into clear, citizen-friendly Telugu. Preserve formatting, spacing, names, and key numbers. Only output the translated text:\n\n{text_to_translate}"
            translated = generate_text_completion(
                system_prompt="You are a translation assistant translating English text to clear, citizen-friendly Telugu.",
                user_prompt=translation_prompt
            )
            return translated
        except Exception:
            return f"[తెలుగు అనువాదం] {text_to_translate}"

@app.post("/api/chat")
async def chat_interaction(request: ChatRequest, db: Session = Depends(get_db)):
    try:
        doc_id = request.document_id
        user_query = request.message
        user_lang = request.language or "english"

        # 1. Verify document exists in database
        doc = db.query(models.Document).filter(models.Document.id == doc_id).first()
        if not doc:
            raise HTTPException(status_code=404, detail="Active document context not found in database.")

        # 2. Write User Message to Database logs
        user_log = models.ChatLog(document_id=doc_id, role="user", content=user_query)
        db.add(user_log)

        # 3. Retrieve matched laws dynamically (RAG)
        search_query = f"{doc.filename} {doc.raw_text} {user_query}"
        matched_laws = retrieve_matching_laws(search_query)
        laws_context_str = json.dumps(matched_laws, indent=2)

        # 4. Generate grounded reply (OpenRouter, Gemini, or Mock Fallback)
        disclaimer = "\n\n---\n*Disclaimer: NyayaMitra provides simplified legal translations based on matched public statutes. This is not formal legal advice. Please consult an advocate before filing appeals.*"
        
        if not GEMINI_API_KEY and not OPENROUTER_API_KEY:
            logger.warning("No API keys configured. Loading matched mock RAG response.")
            matched_law_name = matched_laws[0].get("act") if matched_laws else "General Civil Code"
            matched_law_summary = matched_laws[0].get("summary") if matched_laws else "Verify notices in writing."
            
            assistant_reply = (
                f"Based on your document '{doc.filename}' and matched legal guidelines: **{matched_law_name}**,\n"
                f"here is a helpful response to your query '{user_query}':\n\n"
                f"* Statute: {matched_law_summary}\n"
                f"* Recommendation: Check if your notice lists these parameters and reply within the given deadline.\n"
                f"Let me know if you would like me to draft a dispute letter for you!"
            )
        else:
            # Build grounded RAG chat prompt
            system_prompt = f"""
You are NyayaMitra AI, a citizen-friendly legal translation assistant.
You are helping a citizen understand a legal notice they uploaded.
Provide a simple, clear, and reassuring reply to their question.

DOCUMENT CONTEXT:
Filename: {doc.filename}
Classified Category: {doc.doc_type}
Raw text: {doc.raw_text}

GROUNDING LAWS CONTEXT (RAG):
{laws_context_str}

Instructions:
1. Settle their queries clearly, avoiding complex legalese.
2. Ground your facts solely in the provided document context and matched laws. Do not make up external legal proceedings.
3. Keep it brief (under 150 words).
"""
            if user_lang.lower() == "telugu":
                system_prompt += "\n4. IMPORTANT: You must respond to the citizen in Telugu (తెలుగు) using simple and clear words. Do not reply in English."

            # Format history for prompt wrapper
            history_list = []
            for msg in request.history:
                history_list.append({
                    "role": "user" if msg.role == "user" else "assistant",
                    "content": msg.content
                })

            try:
                reply = generate_text_completion(
                    system_prompt=system_prompt,
                    user_prompt=user_query,
                    history_messages=history_list
                )
                assistant_reply = reply
            except Exception as e:
                logger.error(f"Chat completion call failed: {str(e)}")
                assistant_reply = f"I apologize, I encountered a communication error with our AI engine. Fallback Act match: {matched_laws[0].get('act') if matched_laws else 'General Civil Code'}"
        
        # Translate reply if user language is Telugu
        if user_lang.lower() == "telugu":
            assistant_reply = await perform_translation(assistant_reply, "telugu")
            disclaimer = await perform_translation(disclaimer, "telugu")
            
        assistant_reply += disclaimer
        
        # 5. Write Assistant Message to Database logs
        assistant_log = models.ChatLog(document_id=doc_id, role="assistant", content=assistant_reply)
        db.add(assistant_log)
        
        db.commit()

        return {
            "document_id": doc_id,
            "reply": assistant_reply
        }
    except Exception as e:
        db.rollback()
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(status_code=500, detail=f"Chat database logging failed: {str(e)}")

@app.post("/api/translate")
async def translate_text(request: TranslateRequest):
    translated = await perform_translation(request.text, request.target_language)
    return {"translated_text": translated}

@app.get("/api/calendar")
async def generate_calendar_event(date: str, title: str):
    ics_content = (
        "BEGIN:VCALENDAR\n"
        "VERSION:2.0\n"
        "PRODID:-//NyayaMitra//Milestone Calendar//EN\n"
        f"BEGIN:VEVENT\n"
        f"SUMMARY:{title}\n"
        f"DTSTART;VALUE=DATE:{date.replace('-', '')}\n"
        f"DTEND;VALUE=DATE:{date.replace('-', '')}\n"
        "DESCRIPTION:NyayaMitra AI Legal Notice Deadline Reminder.\n"
        "END:VEVENT\n"
        "END:VCALENDAR\n"
    )
    return {
        "message": f"Calendar event file generated for {title}",
        "ics_file_content": ics_content
    }

@app.get("/api/laws/categories")
async def get_laws_categories(db: Session = Depends(get_db)):
    try:
        categories = db.query(models.Law.category).distinct().all()
        category_list = [c[0] for c in categories if c[0]]
        category_list.sort()
        return category_list
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch categories: {str(e)}")

@app.get("/api/laws")
async def get_laws(category: Optional[str] = None, db: Session = Depends(get_db)):
    try:
        query = db.query(models.Law)
        if category and category.lower() != "all":
            query = query.filter(models.Law.category == category)
        laws = query.all()
        
        formatted_laws = []
        for l in laws:
            try:
                remedies = json.loads(l.remedies_json)
            except Exception:
                remedies = []
            try:
                keywords = json.loads(l.keywords_json)
            except Exception:
                keywords = []
                
            formatted_laws.append({
                "id": l.id,
                "act": l.act,
                "category": l.category,
                "scope": l.scope,
                "summary": l.summary,
                "details": l.details,
                "remedies": remedies,
                "keywords": keywords
            })
        return formatted_laws
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch laws: {str(e)}")

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
